name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:     # Allow manual run from the Actions tab
  schedule:
    - cron: '0 0 * * *'  # Run the workflow every day at 00:00 UTC

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Write the index MarkDown file # docs/index.md
        run: uv run write-index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the mkdocs site
        run: poetry run mkdocs build

      - name: Deploy to gh-pages branch
        run: uv run mkdocs gh-deploy --force