

name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:     # Allow manual run from the Actions tab
  schedule:
    - cron: '0 0 * * *'  # Run the workflow every day at 00:00 UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      
      - name: Use a local virtual environment in .venv directory
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      
      - name: Install the project dependencies
        run: poetry install --no-root # No root skips installing the project itself. There is none.

      - name: Write the Index MarkDwon file
        run: poetry run write-index

      - name: Build the mkdocs site
        run: poetry run mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site